---
title: "recommendation"
format: html
editor: visual
---

```{r loading libraries}
library(tidyverse)
library(janitor)
```

## Loading and Cleaning Data

```{r Loading files}
url = "http://www2.informatik.uni-freiburg.de/~cziegler/BX/BX-CSV-Dump.zip"
download.file(url, destfile = "data.zip")
dir.create("data")
unzip("data.zip",exdir = "data")   

files = paste0("data/",list.files("data"))

ratings = read.csv(files[1], sep = ";") %>% 
  clean_names()
books = read.csv(files[2], sep = ";") %>% 
  clean_names()
users = read.csv(files[3], sep = ";") %>% 
  clean_names()

rm(files, url)
```



```{r adding categories}
set.seed(1234)
categories = c("Action and Adventure","Classic","Detective and Mystery","Fantasy")
books$category = sample( categories, nrow(books), replace=TRUE, prob=c(0.25, 0.3, 0.25, 0.20))
books$category = as.factor(books$category)

rm(categories)
```


```{r}
books$isbn = paste0("Isbn.",books$isbn)
users$user_id = paste0("User.",users$user_id)
ratings$isbn = paste0("Isbn.",ratings$isbn)
ratings$user_id = paste0("User.",ratings$user_id)
```


```{r}
ratings %>%
  group_by(book_rating) %>%
  summarize(cases = n()) %>%
  ggplot(aes(book_rating, cases)) + 
  geom_col() +
  theme_minimal() + 
  scale_x_continuous(breaks = 0:10) 
```

As we can see, there are a lot of zeros. This is a little weird, and it might indicate the absence of rating (a person has read the book but has not rate it). Thus, we will just get with the recommendations that are non-zero.

```{r}
ratings <- ratings %>% 
  filter(book_rating != 0)
```


```{r}
ratings %>%
  group_by(book_rating) %>%
  summarize(cases = n()) %>%
  ggplot(aes(book_rating, cases)) + 
  geom_col() +
  theme_minimal() + 
  scale_x_continuous(breaks = 0:10) 
```

```{r}
ratings_sum <- ratings %>%
  group_by(user_id) %>%
  count() 

summary(ratings_sum$n)
```



```{r}
user_index <- ratings_sum$user_id[ratings_sum$n>4]

users <- users[users$user_id %in% user_index, ]
ratings <- ratings[ratings$user_id %in% user_index, ]
books <- books[books$isbn %in% ratings$isbn,]

rm(ratings_sum, user_index)
```


## Content-Based Recommendation System

















